version: "3.9"

services:
  backend:
    build:
      context: ./backend
    image: myapp-backend:latest
    env_file:
      - ./.env
    ports:
      - "8000:8000"
    restart: unless-stopped

  frontend:
    build:
      context: ./frontend
      args:
        VITE_API_URL: http://localhost:8000
    image: myapp-frontend:latest
    depends_on:
      - backend
    ports:
      - "5173:5173"
    restart: unless-stopped
